[tool.poetry]
name = "py_llm"
version = "0.1.0"
description = ""
authors = ["im"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
tiktoken = "^0.4.0"
streamlit = "^1.24.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
